In [ ]:
import numpy as np
empty_array = np.empty((2, 2))
print("Empty Array:\n", empty_array)
https://colab.research.google.com/drive/1Xg53Ib3JUZj-vvXFREk2JzJUCh0rjNty#scrollTo=zzYuQ-itsXqH

all_ones_array = np.ones((4, 2))
print("All Ones Array:\n", all_ones_array)

fill_array = np.full((3, 3), 7)
print("Array filled with value 7:\n", fill_array)

reference_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(reference_array)
print("Zeros Like Array:\n", zeros_like_array)

ones_like_array = np.ones_like(reference_array)
print("Ones Like Array:\n", ones_like_array)

new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("Numpy Array:\n", numpy_array)

Empty Array:
 [[4.91042627e-310 0.00000000e+000]
 [2.90435030e-144 6.61028939e-310]]
All Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Array filled with value 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Zeros Like Array:
 [[0 0]
 [0 0]]
Ones Like Array:
 [[1 1]
 [1 1]]
Numpy Array:
 [1 2 3 4]


In [ ]:
range_array = np.arange(10, 50)
print("Array ranging from 10 to 49:\n", range_array)

reshaped_array = np.arange(9).reshape((3, 3))
print("3x3 Matrix:\n", reshaped_array)

identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)

random_array = np.random.random(30)
mean_value = random_array.mean()
print("Mean of Random Array:\n", mean_value)

large_random_array = np.random.random((10, 10))
min_value = large_random_array.min()
max_value = large_random_array.max()
print("Minimum Value:", min_value, "Maximum Value:", max_value)

zero_array = np.zeros(10)
zero_array[4] = 1
print("Array with 5th element as 1:\n", zero_array)

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_array = arr[::-1]
print("Reversed Array:\n", reversed_array)

border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("2D Array with Border 1 and Inside 0:\n", border_array)

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("Checkerboard Pattern:\n", checkerboard)

Array ranging from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Mean of Random Array:
 0.5114819470291637
Minimum Value: 0.03941276272735683 Maximum Value: 0.9772271910204648
Array with 5th element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Reversed Array:
 [0 4 0 0 2 1]
2D Array with Border 1 and Inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [1]:
import numpy as np
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

array_sum = x + y
print("Array Sum:\n", array_sum)

array_diff = x - y
print("Array Difference:\n", array_diff)

# 3. Multiply the array with an integer of your choice.
multiplied_array = x * 2
print("Multiplied Array:\n", multiplied_array)

squared_array = x ** 2
print("Squared Array:\n", squared_array)

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("Dot Product v and w:", dot_vw)
print("Dot Product x and v:\n", dot_xv)
print("Dot Product x and y:\n", dot_xy)


Array Sum:
 [[ 6  8]
 [10 13]]
Array Difference:
 [[-4 -4]
 [-4 -3]]
Multiplied Array:
 [[ 2  4]
 [ 6 10]]
Squared Array:
 [[ 1  4]
 [ 9 25]]
Dot Product v and w: 219
Dot Product x and v:
 [29 77]
Dot Product x and y:
 [[19 22]
 [50 58]]


In [ ]:
import numpy as np
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print("A * A^-1:\n", identity)

AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)

AB_T = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)
print("(AB)^T:\n", AB_T)
print("B^T * A^T:\n", BT_AT)

coefficients = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
constants = np.array([-1, -3, 9])
solutions = np.linalg.solve(coefficients, constants)
print("Solutions for Linear Equations:\n", solutions)


A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
Solutions for Linear Equations:
 [ 2.  1. -2.]
